dist: focal
language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'
before_install: pip install --upgrade pip
install: pip install tox-travis
script: tox
notifications:
  email:
    on_failure: change
