__title__ = 'dhis2-pocket-knife'
__description__ = 'Command-line tools for interacting with DHIS2 REST API'
__url__ = 'https://github.com/davidhuser/dhis2-pk'
__version__ = '0.32.3'
__author__ = 'David Huser'
__author_email__ = 'dhuser@baosystems.com'
__license__ = 'MIT'
