name: Package exe with PyInstaller - Windows

on:
  push:
    branches: [ dev-entrypoints ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies with pipenv
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --deploy --dev
        pipenv run pip freeze > pk/requirements.txt

    - name: Test with pytest
      run: |
        pipenv run tests

    - name: PyInstaller Windows
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: pk

    - uses: actions/upload-artifact@v2
      with:
        name: dhis2-pk.exe
        path: pk/dist/windows